In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
iris=pd.read_csv('Iris.csv')

In [3]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [8]:
iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
x={'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3}

In [11]:
iris['Species'].replace(x,inplace=True)

In [12]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [16]:
X=iris.drop(['Id','Species'],axis=1)
y=iris['Species']

In [17]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [18]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Species, dtype: int64

In [74]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=54)

In [75]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
10             5.4           3.7            1.5           0.2
100            6.3           3.3            6.0           2.5
43             5.0           3.5            1.6           0.6
51             6.4           3.2            4.5           1.5
93             5.0           2.3            3.3           1.0
..             ...           ...            ...           ...
23             5.1           3.3            1.7           0.5
15             5.7           4.4            1.5           0.4
130            7.4           2.8            6.1           1.9
69             5.6           2.5            3.9           1.1
111            6.4           2.7            5.3           1.9

[120 rows x 4 columns]

In [76]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
45             4.8           3.0            1.4           0.3
91             6.1           3.0            4.6           1.4
103            6.3           2.9            5.6           1.8
94             5.6           2.7            4.2           1.3
96             5.7           2.9            4.2           1.3
42             4.4           3.2            1.3           0.2
79             5.7           2.6            3.5           1.0
116            6.5           3.0            5.5           1.8
4              5.0           3.6            1.4           0.2
40             5.0           3.5            1.3           0.3
141            6.9           3.1            5.1           2.3
146            6.3           2.5            5.0           1.9
124            6.7           3.3            5.7           2.1
81             5.5           2.4            3.7           1.0
87             6.3           2.3            4.4           1.3
117            7.7           3.8            6.7           2.2
123            6.3           2.7            4.9           1.8
33             5.5           4.2            1.4           0.2
11             4.8           3.4            1.6           0.2
74             6.4           2.9            4.3           1.3
128            6.4           2.8            5.6           2.1
73             6.1           2.8            4.7           1.2
133            6.3           2.8            5.1           1.5
112            6.8           3.0            5.5           2.1
119            6.0           2.2            5.0           1.5
85             6.0           3.4            4.5           1.6
34             4.9           3.1            1.5           0.1
86             6.7           3.1            4.7           1.5
61             5.9           3.0            4.2           1.5

In [77]:
y_train

10     1
100    3
43     1
51     2
93     2
      ..
23     1
15     1
130    3
69     2
111    3
Name: Species, Length: 120, dtype: int64

In [78]:
y_test

0      1
45     1
91     2
103    3
94     2
96     2
42     1
79     2
116    3
4      1
40     1
141    3
146    3
124    3
81     2
87     2
117    3
123    3
33     1
11     1
74     2
128    3
73     2
133    3
112    3
119    3
85     2
34     1
86     2
61     2
Name: Species, dtype: int64

In [79]:
model=SVC()

In [80]:
model.fit(X_train,y_train)

SVC()

In [81]:
p=model.predict(X_test)

In [85]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [86]:
print(confusion_matrix(p,y_test))

[[ 8  0  0]
 [ 0 11  2]
 [ 0  0  9]]


In [87]:
print(classification_report(p,y_test))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      0.85      0.92        13
           3       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.95      0.94        30
weighted avg       0.95      0.93      0.93        30



In [88]:
print(accuracy_score(p,y_test))

0.9333333333333333


In [103]:
def get_answer(a,b,c,d):
    return list(x.keys())[model.predict(np.array([a,b,c,d]).reshape(1,-1))[0]-1]

In [104]:
get_answer(1.2,2.2,3.2,4.2)

C:\Users\manu2\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


'Iris-virginica'